apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.18.2
    releaseName: cilium
    namespace: kube-system
    valuesFile: values.yaml