apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - loadbalancer-ippool.yaml
  - l2-announcement-policy.yaml

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.18.2
    releaseName: cilium
    namespace: kube-system
    valuesFile: values.yaml