# testing purpose
# n8n auto generates enc key on first startup and save into pvc
# cause problem when pvc is deleted and recreated or there are multiple
# replicas, so we use a fixed enc key and save it in k8s secret
existingEncryptionKeySecret: n8n-encryption-key

db:
  type: postgresdb

postgresql:
  enabled: true
  auth:
    database: n8n
    username: n8n
  primary:
    persistence:
      enabled: true
      storageClass: local-path
      size: 8Gi

ingress:
  enabled: true
  className: cilium
  hosts:
    - host: n8n.attat.org
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: n8n-tls
      hosts:
        - n8n.attat.org

main:
  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-path