apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cilium
chartHome: ../../../base/cilium
values:
  operator:
    replicas: 1
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  hubble:
    relay:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi